{
    'name': 'HoReSo Attendances',
    'version': '1.0',
    'category': 'Human Resources/Attendances',
    'summary': 'HoReSo attendance',
    'description': 'Horeso Attendance',
    'sequence': '0',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/employees_view.xml',
        'views/attendance_checkin_form.xml',
        'views/attendance_checkout_form.xml',
        'views/attendance_tree_view.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}